#!/bin/bash -l
#PBS -q {queue}
#PBS -l select={select}
#PBS -l walltime={walltime}
#PBS -W group_list={project}
#PBS -j oe
#PBS -o {log}
#PBS -N {name}
# Generated by autotune.prepare.backends.miyabi: one prepare task per node.
set -uo pipefail
cd "{root}"
RUN_DIRS=({run_dirs})
mapfile -t NODES < <(sort -u "${{PBS_NODEFILE}}")
echo "[JOB] head=$(hostname) date=$(date -Iseconds) nodes=${{#NODES[@]}} tasks=${{#RUN_DIRS[@]}}"
for i in "${{!RUN_DIRS[@]}}"; do
    pbsdsh -n "${{i}}" -- /bin/bash "{root}/scripts/lab/prepare/node_task.sh" "{root}" "${{RUN_DIRS[$i]}}" &
done
wait
overall=0
for d in "${{RUN_DIRS[@]}}"; do
    rc="$(cat "${{d}}/.rc" 2>/dev/null || echo '?')"
    echo "[JOB] $(basename "${{d}}"): rc=${{rc}}"
    [[ "${{rc}}" == "0" ]] || overall=1
done
echo "[JOB] done overall=${{overall}} $(date -Iseconds)"
exit "${{overall}}"
