global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: mysqld
    static_configs:
      - targets: ['localhost:9104']
        labels:
          # DBTune's PromQL filter is {instance="mysqld-exporter:9104"} so we
          # relabel the scrape target's `instance` to match.
          instance: 'mysqld-exporter:9104'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'mysqld-exporter:9104'

  - job_name: node
    static_configs:
      - targets: ['localhost:9100']
        labels:
          instance: 'node-exporter:9100'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'node-exporter:9100'
